name: Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repo Files
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Portus
        uses: docker/login-action@v1
        with:
          registry: https://flotte-docker-registry.spdns.org/
          username: ${{ secrets.PORTUS_USERNAME }}
          password: ${{ secrets.PORTUS_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            flotte-docker-registry.spdns.org/frontend-server:latest
